CREATE TABLE Roles (
    RoleId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    RoleName NVARCHAR(80) NOT NULL UNIQUE,
    Description NVARCHAR(255) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Users (
    UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(120) NOT NULL,
    Email NVARCHAR(180) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId) REFERENCES Roles(RoleId)
);

CREATE TABLE Domains (
    DomainId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DomainCode NVARCHAR(80) NOT NULL UNIQUE,
    DisplayName NVARCHAR(120) NOT NULL,
    OrganizationName NVARCHAR(160) NOT NULL,
    IndustryType NVARCHAR(80) NOT NULL,
    DefaultLanguage NVARCHAR(40) NOT NULL,
    DefaultVoice NVARCHAR(60) NOT NULL,
    WelcomeMessage NVARCHAR(500) NOT NULL,
    FallbackMessage NVARCHAR(500) NOT NULL,
    EscalationMessage NVARCHAR(500) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE DomainIntents (
    IntentId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DomainId UNIQUEIDENTIFIER NOT NULL,
    IntentCode NVARCHAR(100) NOT NULL,
    IntentLabel NVARCHAR(120) NOT NULL,
    Description NVARCHAR(255) NULL,
    Priority INT NOT NULL DEFAULT 100,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DomainIntents_Domains FOREIGN KEY (DomainId) REFERENCES Domains(DomainId),
    CONSTRAINT UQ_DomainIntents UNIQUE (DomainId, IntentCode)
);

CREATE TABLE DomainRules (
    RuleId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DomainId UNIQUEIDENTIFIER NOT NULL,
    RuleType NVARCHAR(60) NOT NULL,
    RuleText NVARCHAR(1000) NOT NULL,
    Priority INT NOT NULL DEFAULT 100,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DomainRules_Domains FOREIGN KEY (DomainId) REFERENCES Domains(DomainId)
);

CREATE TABLE PromptTemplates (
    PromptTemplateId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DomainId UNIQUEIDENTIFIER NOT NULL,
    PromptType NVARCHAR(60) NOT NULL,
    TemplateText NVARCHAR(MAX) NOT NULL,
    VersionNo INT NOT NULL DEFAULT 1,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_PromptTemplates_Domains FOREIGN KEY (DomainId) REFERENCES Domains(DomainId)
);

CREATE TABLE ToolDefinitions (
    ToolId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DomainId UNIQUEIDENTIFIER NOT NULL,
    ToolName NVARCHAR(120) NOT NULL,
    Description NVARCHAR(255) NOT NULL,
    SchemaJson NVARCHAR(MAX) NOT NULL,
    HandlerName NVARCHAR(180) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ToolDefinitions_Domains FOREIGN KEY (DomainId) REFERENCES Domains(DomainId),
    CONSTRAINT UQ_ToolDefinitions UNIQUE (DomainId, ToolName)
);

CREATE TABLE DomainFields (
    FieldId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DomainId UNIQUEIDENTIFIER NOT NULL,
    FieldCode NVARCHAR(100) NOT NULL,
    Label NVARCHAR(120) NOT NULL,
    DataType NVARCHAR(40) NOT NULL,
    IsRequired BIT NOT NULL DEFAULT 0,
    SortOrder INT NOT NULL DEFAULT 100,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DomainFields_Domains FOREIGN KEY (DomainId) REFERENCES Domains(DomainId),
    CONSTRAINT UQ_DomainFields UNIQUE (DomainId, FieldCode)
);

CREATE TABLE EscalationPolicies (
    EscalationPolicyId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DomainId UNIQUEIDENTIFIER NOT NULL,
    PolicyCode NVARCHAR(80) NOT NULL,
    TriggerType NVARCHAR(80) NOT NULL,
    TriggerConfigJson NVARCHAR(MAX) NOT NULL,
    Priority INT NOT NULL DEFAULT 100,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_EscalationPolicies_Domains FOREIGN KEY (DomainId) REFERENCES Domains(DomainId)
);

CREATE TABLE Agents (
    AgentId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(120) NOT NULL,
    Email NVARCHAR(180) NOT NULL UNIQUE,
    SkillGroup NVARCHAR(120) NULL,
    AvailabilityStatus NVARCHAR(40) NOT NULL DEFAULT 'offline',
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Conversations (
    ConversationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DomainId UNIQUEIDENTIFIER NOT NULL,
    ChannelType NVARCHAR(40) NOT NULL,
    CustomerIdentifier NVARCHAR(180) NULL,
    SessionStatus NVARCHAR(40) NOT NULL,
    CurrentIntent NVARCHAR(120) NULL,
    StartedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    EndedAt DATETIME2 NULL,
    EscalatedToAgent BIT NOT NULL DEFAULT 0,
    AssignedAgentId UNIQUEIDENTIFIER NULL,
    SummaryText NVARCHAR(MAX) NULL,
    CONSTRAINT FK_Conversations_Domains FOREIGN KEY (DomainId) REFERENCES Domains(DomainId),
    CONSTRAINT FK_Conversations_Agents FOREIGN KEY (AssignedAgentId) REFERENCES Agents(AgentId)
);

CREATE TABLE ConversationMessages (
    MessageId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER NOT NULL,
    SpeakerType NVARCHAR(40) NOT NULL,
    MessageType NVARCHAR(40) NOT NULL,
    MessageText NVARCHAR(MAX) NOT NULL,
    SequenceNo INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ConversationMessages_Conversations FOREIGN KEY (ConversationId) REFERENCES Conversations(ConversationId)
);

CREATE TABLE ToolExecutions (
    ExecutionId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER NOT NULL,
    ToolName NVARCHAR(120) NOT NULL,
    RequestJson NVARCHAR(MAX) NOT NULL,
    ResponseJson NVARCHAR(MAX) NULL,
    ExecutionStatus NVARCHAR(40) NOT NULL,
    StartedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CompletedAt DATETIME2 NULL,
    ErrorText NVARCHAR(MAX) NULL,
    CONSTRAINT FK_ToolExecutions_Conversations FOREIGN KEY (ConversationId) REFERENCES Conversations(ConversationId)
);

CREATE TABLE Escalations (
    EscalationId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER NOT NULL,
    EscalationReason NVARCHAR(255) NOT NULL,
    EscalatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    AssignedAgentId UNIQUEIDENTIFIER NULL,
    AcceptedAt DATETIME2 NULL,
    ClosedAt DATETIME2 NULL,
    CONSTRAINT FK_Escalations_Conversations FOREIGN KEY (ConversationId) REFERENCES Conversations(ConversationId),
    CONSTRAINT FK_Escalations_Agents FOREIGN KEY (AssignedAgentId) REFERENCES Agents(AgentId)
);

CREATE TABLE AuditLogs (
    AuditId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ActorType NVARCHAR(40) NOT NULL,
    ActorId NVARCHAR(120) NOT NULL,
    ActionName NVARCHAR(120) NOT NULL,
    EntityType NVARCHAR(80) NOT NULL,
    EntityId NVARCHAR(120) NOT NULL,
    PayloadJson NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
